import { usePage } from '@inertiajs/react';
import {
    IconAdjustments,
    IconArrowsExchange,
    IconBook2,
    IconBuildingBank,
    IconChecklist,
    IconClipboardCheck,
    IconCoin,
    IconDatabase,
    IconFileDescription,
    IconLayout2,
    IconReportAnalytics,
    IconSettings,
    IconTable,
    IconWallet,
    IconUserBolt,
    IconUserShield,
    IconUsers,
    IconCirclePlus,
} from '@tabler/icons-react';
import hasAnyPermission from './Permissions';
import React from 'react';

export default function Menu() {
    const { url } = usePage();

    const menuNavigation = [
        {
            title: 'Cash Management',
            permissions: hasAnyPermission(['cash-management-access']),
            details: [
                {
                    title: 'Dashboard',
                    href: '/apps/dashboard',
                    active: url.startsWith('/apps/dashboard'),
                    icon: <IconLayout2 size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['dashboard-access']),
                },
                {
                    title: 'Master Data',
                    icon: <IconDatabase size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['master-data-access']) || hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Business Unit / Company', href: '/apps/cash-management/workspace/master-data/business-unit-company', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Departemen', href: '/apps/cash-management/workspace/master-data/departemen', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Cost Center / Project', href: '/apps/cash-management/workspace/master-data/cost-center-project', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Vendor / Supplier', href: '/apps/cash-management/workspace/master-data/vendor-supplier', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Customer', href: '/apps/cash-management/workspace/master-data/customer', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Bank & Cash Account', href: '/apps/cash-management/workspace/master-data/bank-cash-account', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'COA / Chart of Account', href: '/apps/cash-management/workspace/master-data/chart-of-account', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Transaction Category', href: '/apps/cash-management/workspace/master-data/transaction-category', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Payment Method', href: '/apps/cash-management/workspace/master-data/payment-method', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Currency', href: '/apps/cash-management/workspace/master-data/currency', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Tax Master', href: '/apps/cash-management/workspace/master-data/tax-master', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Document Type', href: '/apps/cash-management/workspace/master-data/document-type', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Attachment Category', href: '/apps/cash-management/workspace/master-data/attachment-category', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Payment Request',
                    icon: <IconFileDescription size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['payment-requests-access']) || hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Semua Payment Request', href: '/apps/cash-management/payment-requests', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Buat Payment Request', href: '/apps/cash-management/payment-requests', icon: <IconCirclePlus size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Draft Request', href: '/apps/cash-management/workspace/payment-request/draft-request', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Menunggu Approval', href: '/apps/cash-management/workspace/payment-request/menunggu-approval', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Request Direvisi', href: '/apps/cash-management/workspace/payment-request/request-direvisi', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Request Ditolak', href: '/apps/cash-management/workspace/payment-request/request-ditolak', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Request Disetujui', href: '/apps/cash-management/workspace/payment-request/request-disetujui', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Siap Dibayar', href: '/apps/cash-management/workspace/payment-request/siap-dibayar', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Riwayat Payment Request', href: '/apps/cash-management/workspace/payment-request/riwayat-payment-request', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Approval',
                    icon: <IconClipboardCheck size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['approvals-access']) || hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Menunggu Persetujuan Saya', href: '/apps/cash-management/approvals', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Semua Approval', href: '/apps/cash-management/workspace/approval/semua-approval', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Approval Payment Request', href: '/apps/cash-management/workspace/approval/approval-payment-request', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Approval Kas Kecil', href: '/apps/cash-management/workspace/approval/approval-kas-kecil', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Approval Transfer', href: '/apps/cash-management/workspace/approval/approval-transfer', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Approval Adjustment', href: '/apps/cash-management/workspace/approval/approval-adjustment', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Riwayat Approval', href: '/apps/cash-management/workspace/approval/riwayat-approval', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Execute Cash',
                    icon: <IconWallet size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['treasury-access']) || hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Pembayaran Siap Dieksekusi', href: '/apps/cash-management/treasury', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Execute Payment', href: '/apps/cash-management/workspace/execute-cash/execute-payment', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Pembayaran Sebagian', href: '/apps/cash-management/workspace/execute-cash/pembayaran-sebagian', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Pembayaran Pending', href: '/apps/cash-management/workspace/execute-cash/pembayaran-pending', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Pembayaran Selesai', href: '/apps/cash-management/workspace/execute-cash/pembayaran-selesai', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Bukti Pembayaran', href: '/apps/cash-management/workspace/execute-cash/bukti-pembayaran', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Riwayat Pembayaran', href: '/apps/cash-management/workspace/execute-cash/riwayat-pembayaran', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Cash Receipt',
                    icon: <IconCoin size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Semua Penerimaan', href: '/apps/cash-management/workspace/cash-receipt/semua-penerimaan', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Input Penerimaan', href: '/apps/cash-management/workspace/cash-receipt/input-penerimaan', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Penerimaan Customer', href: '/apps/cash-management/workspace/cash-receipt/penerimaan-customer', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Penerimaan Lainnya', href: '/apps/cash-management/workspace/cash-receipt/penerimaan-lainnya', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Transfer Masuk', href: '/apps/cash-management/workspace/cash-receipt/transfer-masuk', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Adjustment Masuk', href: '/apps/cash-management/workspace/cash-receipt/adjustment-masuk', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Riwayat Penerimaan', href: '/apps/cash-management/workspace/cash-receipt/riwayat-penerimaan', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Transfer Internal',
                    icon: <IconArrowsExchange size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Transfer Antar Kas/Bank', href: '/apps/cash-management/workspace/transfer-internal/transfer-antar-kas-bank', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Daftar Transfer', href: '/apps/cash-management/workspace/transfer-internal/daftar-transfer', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Transfer Pending', href: '/apps/cash-management/workspace/transfer-internal/transfer-pending', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Transfer Selesai', href: '/apps/cash-management/workspace/transfer-internal/transfer-selesai', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Riwayat Transfer', href: '/apps/cash-management/workspace/transfer-internal/riwayat-transfer', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Petty Cash',
                    icon: <IconChecklist size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Saldo Kas Kecil', href: '/apps/cash-management/workspace/petty-cash/saldo-kas-kecil', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Permintaan Dana', href: '/apps/cash-management/workspace/petty-cash/permintaan-dana', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Penggunaan Kas Kecil', href: '/apps/cash-management/workspace/petty-cash/penggunaan-kas-kecil', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Pengisian Kembali', href: '/apps/cash-management/workspace/petty-cash/pengisian-kembali', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Pertanggungjawaban', href: '/apps/cash-management/workspace/petty-cash/pertanggungjawaban', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Riwayat Kas Kecil', href: '/apps/cash-management/workspace/petty-cash/riwayat-kas-kecil', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Reconciliation',
                    icon: <IconAdjustments size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['reconciliation-access']) || hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Rekonsiliasi Bank', href: '/apps/cash-management/reconciliation', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Rekonsiliasi Kas', href: '/apps/cash-management/workspace/reconciliation/rekonsiliasi-kas', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Upload Mutasi Bank', href: '/apps/cash-management/workspace/reconciliation/upload-mutasi-bank', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Matching Transaksi', href: '/apps/cash-management/workspace/reconciliation/matching-transaksi', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Selisih Rekonsiliasi', href: '/apps/cash-management/workspace/reconciliation/selisih-rekonsiliasi', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Riwayat Rekonsiliasi', href: '/apps/cash-management/workspace/reconciliation/riwayat-rekonsiliasi', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Journal & Posting',
                    icon: <IconBook2 size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Draft Posting', href: '/apps/cash-management/workspace/journal-posting/draft-posting', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Transaksi Sudah Posting', href: '/apps/cash-management/workspace/journal-posting/transaksi-sudah-posting', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Jurnal Otomatis', href: '/apps/cash-management/workspace/journal-posting/jurnal-otomatis', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Jurnal Manual Adjustment', href: '/apps/cash-management/workspace/journal-posting/jurnal-manual-adjustment', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Reversal / Cancel Journal', href: '/apps/cash-management/workspace/journal-posting/reversal-cancel-journal', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Riwayat Posting', href: '/apps/cash-management/workspace/journal-posting/riwayat-posting', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Reports',
                    icon: <IconReportAnalytics size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['reports-access']) || hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Laporan Saldo Kas & Bank', href: '/apps/cash-management/reports', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Laporan Arus Kas', href: '/apps/cash-management/workspace/reports/laporan-arus-kas', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Laporan Payment Request', href: '/apps/cash-management/workspace/reports/laporan-payment-request', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Laporan Pengeluaran', href: '/apps/cash-management/workspace/reports/laporan-pengeluaran', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Laporan Penerimaan', href: '/apps/cash-management/workspace/reports/laporan-penerimaan', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Laporan Transfer Internal', href: '/apps/cash-management/workspace/reports/laporan-transfer-internal', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Laporan Kas Kecil', href: '/apps/cash-management/workspace/reports/laporan-kas-kecil', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Outstanding Approval', href: '/apps/cash-management/workspace/reports/outstanding-approval', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Payment Due List', href: '/apps/cash-management/workspace/reports/payment-due-list', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Vendor Payment Report', href: '/apps/cash-management/workspace/reports/vendor-payment-report', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Cost Center Expense', href: '/apps/cash-management/workspace/reports/cost-center-expense', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Cash Movement', href: '/apps/cash-management/workspace/reports/cash-movement', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Audit Trail', href: '/apps/cash-management/workspace/reports/audit-trail', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Activity Log', href: '/apps/cash-management/workspace/reports/activity-log', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Documents & Audit',
                    icon: <IconBuildingBank size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Arsip Dokumen', href: '/apps/cash-management/workspace/documents-audit/arsip-dokumen', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Lampiran Transaksi', href: '/apps/cash-management/workspace/documents-audit/lampiran-transaksi', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Audit Trail', href: '/apps/cash-management/workspace/documents-audit/audit-trail', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Log Aktivitas User', href: '/apps/cash-management/workspace/documents-audit/log-aktivitas-user', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'History Perubahan Data', href: '/apps/cash-management/workspace/documents-audit/history-perubahan-data', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Temuan Audit', href: '/apps/cash-management/workspace/documents-audit/temuan-audit', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
                {
                    title: 'Settings',
                    icon: <IconSettings size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['administration-access']) || hasAnyPermission(['cash-management-access']),
                    subdetails: [
                        { title: 'Profil Perusahaan', href: '/apps/cash-management/workspace/settings/profil-perusahaan', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Periode Akuntansi', href: '/apps/cash-management/workspace/settings/periode-akuntansi', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Penomoran Dokumen', href: '/apps/cash-management/workspace/settings/penomoran-dokumen', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'User', href: '/apps/cash-management/workspace/settings/user', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Role', href: '/apps/cash-management/workspace/settings/role', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Permission', href: '/apps/cash-management/workspace/settings/permission', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Role Menu Access', href: '/apps/cash-management/workspace/settings/role-menu-access', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Workflow Approval', href: '/apps/cash-management/workspace/settings/workflow-approval', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Approval Matrix', href: '/apps/cash-management/workspace/settings/approval-matrix', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Approval Level', href: '/apps/cash-management/workspace/settings/approval-level', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Notifikasi Sistem', href: '/apps/cash-management/workspace/settings/notifikasi-sistem', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Template Export / Print', href: '/apps/cash-management/workspace/settings/template-export-print', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Integrasi Sistem', href: '/apps/cash-management/workspace/settings/integrasi-sistem', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Backup & Restore', href: '/apps/cash-management/workspace/settings/backup-restore', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                        { title: 'Preferensi Aplikasi', href: '/apps/cash-management/workspace/settings/preferensi-aplikasi', icon: <IconTable size={18} strokeWidth={1.5} />, permissions: true },
                    ],
                },
            ],
        },
        {
            title: 'User Management',
            permissions:
                hasAnyPermission(['permissions-access']) ||
                hasAnyPermission(['roles-access']) ||
                hasAnyPermission(['users-access']),
            details: [
                {
                    title: 'Hak Akses',
                    href: '/apps/permissions',
                    active: url.startsWith('/apps/permissions'),
                    icon: <IconUserBolt size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['permissions-access']),
                },
                {
                    title: 'Akses Group',
                    href: '/apps/roles',
                    active: url.startsWith('/apps/roles'),
                    icon: <IconUserShield size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['roles-access']),
                },
                {
                    title: 'Pengguna',
                    icon: <IconUsers size={20} strokeWidth={1.5} />,
                    permissions: hasAnyPermission(['users-access']),
                    subdetails: [
                        {
                            title: 'Data Pengguna',
                            href: '/apps/users',
                            icon: <IconTable size={20} strokeWidth={1.5} />,
                            active: url === '/apps/users',
                            permissions: hasAnyPermission(['users-data']),
                        },
                        {
                            title: 'Tambah Data Pengguna',
                            href: '/apps/users/create',
                            icon: <IconCirclePlus size={20} strokeWidth={1.5} />,
                            active: url === '/apps/users/create',
                            permissions: hasAnyPermission(['users-create']),
                        },
                    ],
                },
            ],
        },
    ];

    return menuNavigation;
}
